version: '3'
services:
  postgres:
    image: postgres:9.5
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - /Users/anton/pg_blog:/Users/anton/pg_blog
    environment:
      - POSTGRES_PASSWORD=12345
      - PGDATA=/Users/anton/pg_data
      - POSTGRES_USER=postgres