version: '3'
services:
  postgres:
    image: postgres:9.5
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - ${VOLUMES}:${VOLUMES}
    environment:
      - POSTGRES_PASSWORD=12345
      - PGDATA=${ENVPGDATA}
      - POSTGRES_USER=postgres